data types:
  - name: diag_urma_t
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_t.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: diag_urma_q
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_q.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: diag_urma_ps
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_ps.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: diag_urma_uv
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_uv.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: diag_urma_cei
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_cei.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: diag_urma_gst
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_gst.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: diag_urma_hwv
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_hwv.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: diag_urma_tca
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_tca.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: diag_urma_vis
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_vis.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: diag_urma_wst
    type: diag
    file_obs_type: conv_t
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: diag_urma_wst.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: anal_urma
    type: anal
    file_obs_type: anl
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: anal_urma.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5

  - name: ges_urma
    type: anal
    file_obs_type: ges
    model_domain: urma2p5
    num_tasks: 12
    batch_days: 15
    mapping: anal_urma.py
    directory: /scratch5/purged/Xin.C.Jin/reg_ocelot/temp_prod_archive_urma2p5